### ISSUE TITLE
Chokes on valid `pyproject.toml`.

### ISSUE THREAD

**Issue by emcd** [guilatrova/tryceratops#71]
Other tools can successfully parse my `pyproject.toml` but Tryceratops cannot because it is using an outdated TOML library, `toml`, which does fully support the TOML 1.0 specification.

```
$ hatch --env develop run tryceratops
Traceback (most recent call last):
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/bin/tryceratops", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/tryceratops/__main__.py", line 66, in main
    entrypoint(prog_name="tryceratops")
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/tryceratops/__main__.py", line 48, in entrypoint
    pyproj_config = load_config(dir)
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/tryceratops/files/discovery.py", line 118, in load_config
    config = toml.load(toml_file)
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/home/me/.local/share/hatch/env/virtual/accretive/5On6b-gH/develop/lib/python3.8/site-packages/toml/decoder.py", line 362, in loads
    raise TomlDecodeError("Unterminated string found."
toml.decoder.TomlDecodeError: Unterminated string found. Reached end of file. (line 292 column 1 char 8542)
```

PR #70 fixes this problem by using `tomli`, which is also known as `tomllib` in the Python 3.11 and later standard library.

**Comment by emcd** [comment]
Closed by #70, which is incorporated into 2.3.3.
